version: '3'
services:
  back:
    container_name: back
    build:
      context: ./api
      dockerfile: ./docker/dev/Dockerfile
    command: sh -c "npm install && npm start"
    ports:
      - 4001:4001
    volumes:
      - ./api/:/usr/src/app
  front:
    container_name: front
    build:
      context: ./web
      dockerfile: ./docker/dev/Dockerfile
    command: sh -c "npm install && npm start"
    ports:
      - 3001:3000
    volumes:
      - ./web/:/usr/src/app
    links:
      - back
